### ISSUE TITLE
File path error

### ISSUE THREAD

**Issue by Xinshi0726** [Kasumigaoka-Utaha/Pytorch-implementation-of-DeepRegressionForests#1]
Hi,
When I tried to run the script, there was an error saying that the images are under the wrong file path. After careful inspection, I found that there's no 'train' folder under the path FGNET/images. But I got the dataset using wget. Is there any preprocessing I need to do?
![image](https://user-images.githubusercontent.com/46645292/145752514-49530168-af0d-44e9-80a4-f63ddd00651a.png)
![image](https://user-images.githubusercontent.com/46645292/145752559-d4b6cad6-0521-4eb7-a42e-4541c237209d.png)
![image](https://user-images.githubusercontent.com/46645292/145752613-c5f1b6f7-db99-459e-93b5-eaef714f7799.png)

**Comment by Kasumigaoka-Utaha** [comment]
Since I didn't upload the training dataset to the github(it is too large...), you can download it by yourself...

**Comment by Kasumigaoka-Utaha** [comment]
Maybe you should check whether you put the train.csv and test.csv at right place, since my code just read the training dataset from train.csv to determine whether the image should be put into train.csv...

**Comment by Kasumigaoka-Utaha** [comment]
Also, you can check whether your FGNET was put at the right place, since I failed to upload the whole dataset onto github...

**Comment by Xinshi0726** [comment]
Thanks!

**Comment by ujnhj** [comment]
ModuleNotFoundError: No module named 'defaults'

**Comment by ujnhj** [comment]
> ModuleNotFoundError: No module named 'defaults'

How to solve this problem

**Comment by AAAceerr** [comment]
请问你解决这个问题了吗
ModuleNotFoundError：没有名为 'defaults' 的模块

似乎还有这样的问题--File "train.py", line 102, in <module>
    main()
  File "train.py", line 60, in main
    train_dataset = FaceDataset(args.data_dir, "train", img_size=cfg.MODEL.IMG_SIZE, augment=True,
  File "/root/anaconda3/envs/drf/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: MODEL
